toolbar:
  - styleselect | forecolor backcolor | bold underline italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent
  - undo redo | image | link | table
plugins:
  - 'advlist autolink lists link image charmap print preview hr anchor pagebreak'
  - 'searchreplace wordcount visualblocks visualchars code'
  - 'insertdatetime media nonbreaking save table contextmenu directionality'
  - 'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc help'
